apiVersion: v1
kind: Service
metadata:
  name: nginx-hello-world
  namespace: istio-system
spec:
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 80
  type: ClusterIP
  selector:
    run: nginx-hello-world

