apiVersion: extension/v1beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hello-docker
  namespace: istio-system
spec:
  scalRef:
    kind: Deployment
    name: hello-docker
    subresource: scale
  minReplicas: 1
  maxReplicas: 10
  cpuUtilization:
    targetPercentage: 50
